### ISSUE TITLE
Prefixes used in document schemas but declared in the general schema are not being resolved

### ISSUE THREAD

**Issue by AlexSerrano22** [CarbonLDP/carbonldp-js-sdk#215] opened 2018-01-26 06:28 UTC
Hi, I retrieve my data with the method getMembers("documentIRI", _ => _ .properties({ "properties..." })) but sometimes the object that I retrieve is incorrect whether the object missing some property or has a property that I delete from the "query". I add some examples of that:

carbon code:
```
carbon.documents.getMembers( "/skills/", _ => _
        .properties( {
          "name": _.inherit,
          "skillLevels": {
            "query": _ => _
              .withType( "https://tms.base22.com/ns#SkillLevel" )
              .properties( {
                "name": _.inherit,
              } )
          }
        } )).then(([results, response]) => {
          this.skills = results;
      });
```
Result:
<img width="842" alt="screen shot 2018-01-26 at 12 20 35 am" src="https://user-images.githubusercontent.com/5456395/35427416-e4c35eac-022e-11e8-9c40-727115efe4ef.png">

Carbon code:
in this case, I remove the name property
```
carbon.documents.getMembers( "/skills/", _ => _
        .properties( {
          "description": _.inherit,
        } )).then(([results, response]) => {
          this.skills = results;
      });
```
<img width="721" alt="screen shot 2018-01-26 at 12 22 45 am" src="https://user-images.githubusercontent.com/5456395/35427462-2d8119f4-022f-11e8-9101-c17d9c9dde2e.png">

and never obtain the skill levels with his names

my schemas are these:

```
SKILL: {
    "name": {
      "@id": "https://schema.org/name",
      "@type": "string"
    },
    "description": {
      "@id": "https://schema.org/description",
      "@type": "string"
    },
    "skillLevels": {
      "@id": "tms:skillLevel",
      "@type": "@id",
      "@container": "@set"
    }
  },
  SKILL_LEVEL: {
    "name": {
      "@id": "https://schema.org/name",
      "@type": "string"
    },
    "description": {
      "@id": "https://schema.org/description",
      "@type": "string"
    },
    "skill": {
      "@id": "tms:skill",
      "@type": "@id"
    }
  },

```

do you have some idea of what is happening?

**Comment by roddolf** [comment] 2018-01-26 15:23
Hi Alex, this is the expected behavior.

Remember that the SDK maintains a reference of every document (cache), so even of the queries request different properties, the data will be merge in the same document.

**Comment by AlexSerrano22** [comment] 2018-01-26 22:19
Hi @roddolf, I understand that, but my major issue here is that sometimes I received all data, and in other, I don't receive the skill levels ( that is the data that I need to render a component ) If I refresh the browser I obtain different data with the same query.

**Comment by roddolf** [comment] 2018-01-26 22:46
Oh, I get it now.

It may be because of the `.withType( "https://tms.base22.com/ns#SkillLevel" )` ?
This is also a filter, so if the `skillLevel` documents does not have it in their `types` array, the document will not be retrieved.

But it is weird that refreshing gives you different data.
Can you provide the query the SDK is sending to the platform, accessing in the network tab of the dev tools?

**Comment by AlexSerrano22** [comment] 2018-01-27 15:52
sure, this is the query:
```
PREFIX tms: <https://tms.base22.com/ns#> PREFIX c: <https://carbonldp.com/ns/v1/platform#> CONSTRUCT { ?metadata a c:VolatileResource, c:QueryMetadata; c:target ?member. ?member a ?member__types; <https://schema.org/name> ?member__name; tms:skillLevel ?member__skillLevels. ?member__skillLevels a ?member__skillLevels__types; <https://schema.org/name> ?member__skillLevels__name } WHERE { BIND(BNODE() AS ?metadata). { SELECT ?member WHERE { <http://carbonldp.webtraining.zone:8083/skills/> <http://www.w3.org/ns/ldp#membershipResource> ?membershipResource; <http://www.w3.org/ns/ldp#hasMemberRelation> ?hasMemberRelation. ?membershipResource ?hasMemberRelation ?member } }. OPTIONAL { ?member a ?member__types }. OPTIONAL { ?member <https://schema.org/name> ?member__name. FILTER( datatype( ?member__name ) = <http://www.w3.org/2001/XMLSchema#string> ) }. OPTIONAL { ?member tms:skillLevel ?member__skillLevels. FILTER( ! isLiteral( ?member__skillLevels ) ). OPTIONAL { ?member__skillLevels a ?member__skillLevels__types }. ?member__skillLevels a tms:SkillLevel. OPTIONAL { ?member__skillLevels <https://schema.org/name> ?member__skillLevels__name. FILTER( datatype( ?member__skillLevels__name ) = <http://www.w3.org/2001/XMLSchema#string> ) } } }
```
this is one of my skill levels
http://carbonldp.webtraining.zone:8083/skill-levels/2233934286131316470/

and this is the documents that I reiceived: 
<img width="467" alt="screen shot 2018-01-27 at 9 50 40 am" src="https://user-images.githubusercontent.com/5456395/35473542-9506bd86-0347-11e8-8e8d-de1346e9f967.png">

**Comment by roddolf** [comment] 2018-01-27 18:09
I cannot reproduce it.
I take the liberty to send a request at your endpoint and its retrieving the correct data.

Which version of the SDK are you working with?
The `alpha-8` had an error merging query data, but it should be working with the `alpha-9`

**Comment by AlexSerrano22** [comment] 2018-01-27 23:45
yes, I'm working with the `alpha-9`, I recorded my screen to show you what is happening: 
https://www.youtube.com/watch?v=G1w8ws_z2R8
could you show me how do you sent the request to my end point? maybe I have a typo error or something like that.

thanks

**Comment by AlexSerrano22** [comment] 2018-01-28 00:25
I think I could solve it, I used this "query":
```
CarbonService.retrieveCarbon().documents.getMembers('/skills/',
      _ => _.withType(`https://tms.base22.com/ns#Skill`).
      properties({
        '@id': _.inherit,
        'name': _.inherit,
        'skillLevels': {
          'query': _ => _.withType(`https://tms.base22.com/ns#SkillLevel`).
          properties({
            'name': _.inherit
          })
        }
      })
```
and the results are what I expeted. 

finally: is necessary include the type of the first elements (parent)? in this case: 
`.withType(`https://tms.base22.com/ns#Skill`).`

**Comment by roddolf** [comment] 2018-01-28 00:33
Thanks, that confirms my findings.

Its a problem when resolving the `prefixes`.
You have the `skillsLevels` as `tms:skillLevel`, and is not been resolved in your side.
Mine was, because I added the `tms` prefix in the same declaration of the schema.

Lastly, is not necessarily to include the type, but its better. Since the SDK will not have the search the property declaration between every schema you have declared.

**Closed** 2018-02-09 01:26 UTC
Labels: bug: verified, in progress, priority2: required, type: bug
